#!/bin/bash
#
# DESCRIPTION
#	Invoke release build
#
# USAGE:
#	Steps to invoke this script.
#		export NLEXTERNALDIR=<path>
#		export BUILD_NUMBER=<#>
#		source setEnv
#		./buildRelease
#
# HUDSON BUILD:
#	cd $WORKSPACE
#	export NLEXTERNALDIR=c:/hudson/jobs/source_main_external/workspace
#	source setEnv
#	./buildRelease
#
# DEBUG:
#	To debug ANT problems, add -v option to an ANT command. For example:
#		$ANT -v -f scripts/build_xlib.xml

if [ "X${JAVA_HOME}" = "X" ] ; then
	export JAVA_HOME=$NLEXTERNALDIR/j2sdk/jdk1.7.0_71
fi
export ANT_HOME=$NLEXTERNALDIR/apache-ant/apache-ant-1.7.0

ANT=$ANT_HOME/bin/ant
LOG_FILE=buildRelease.log
BUILD_MANIFEST_FILE=build.manifest

(
set -x
# Extract Perforce Workspace and Hudson info (only if running on Hudson)
if [ -f ../config.xml ]; then
	scripts/getPerforceWorkspace.pl ../config.xml
fi

# Prepare environment
chmod +x ./configure
./configure --type=release || exit $?
source build.config

# Prepare dependencies
$ANT -f scripts/build_xlib.xml || exit $?
#scripts/checkBuildLog.pl $LOG_FILE || exit $?

# Compile code and build installers
export ANT_OPTS="-Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=512m"
export ANT_ARGS="-Dnlbuildroot=$NLBUILDROOT -Dnlexternaldir=$NLEXTERNALDIR -Dversion_str=$VERSION_STR -Dversion_build_short=$VERSION_BUILD_SHORT -Dbuild_date_long=$BUILD_DATE_LONG"
$ANT -f scripts/build_compile.xml || exit $?
#scripts/checkBuildLog.pl $LOG_FILE || exit $?

# Publish intstallers and artifacts
$ANT -f scripts/build_publish.xml || exit $?
#scripts/checkBuildLog.pl $LOG_FILE || exit $?

# Create and publish build manifest
scripts/createBuildManifest.pl $LOG_FILE > $BUILD_MANIFEST_FILE || exit $?
$ANT -f scripts/build_publish.xml manifest || exit $?
set +x
) 2>&1 | tee $LOG_FILE

echo $VERSION_STR
echo $VERSION_BUILD_SHORT


export TTTT="S:/build/release_candidate/ProfessionalServices/RMSTOSKYDRMConverter/$VERSION_STR/$VERSION_BUILD_SHORT"
cd $TTTT
ls
export ARTIFACT_FILENAME=`ls | grep *.zip`
echo $ARTIFACT_FILENAME

exit ${PIPESTATUS[0]}
